import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className='bg-green-500'>Building hulu</h2>

      {/* Header */}

      {/* Nav */}

      {/* Container */}
    </div>
  )
}
